export const terms = [
  'Appointments you book through our Sites as a Snailz account holder are offers that you purchase from participating salons through our service. The bookings are redeemable for certain goods, services or experiences offered by, or facilitated through, the salons identified on the appointment details. The salon is solely responsible for providing the service. The salon is the issuer of the offer and is fully responsible for all goods and services it provides to you and for any and all injuries, illnesses, damages, claims, liabilities and costs ("Liabilities") it may cause you to suffer, directly or indirectly, in full or in part, whether related to the appointment booking or not. You waive and release Snailz and its subsidiaries, affiliates, partners, officers, directors, employees and agents from any Liabilities arising from or related to any act or omission of a salon in connection with your use of an appointment or the services/goods it provides in connection with it.',

  'By booking an appointment you agree to the terms of this Agreement and these Terms of Sale. By purchasing, viewing a mobile version, printing, accepting, using or attempting to complete an appointment, you agree to these Terms of Sale specifically ("rules"), the terms on the offer details itself (collectively, the "fine print" regardless of how labeled). These rules apply to all promotions that we make available, unless a particular offer’s fine print states otherwise, and except as otherwise required by law. In the event of a conflict between these rules and a offer’s fine print, the offer’s fine print will control.',

  'Your card will be charged at your appointment time unless cancelled on Snailz beforehand. Should the Customer complete the appointment but is unhappy with the service received, requests for refunds or adjustments should be directed to the serving salon. Snailz reserves the right to issue refunds requested by customers at its sole discretion for non-service quality related disputes.',

  'Snailz may refund any amounts in the original form of payment or may issue a credit towards future purchases.',

  'By transacting through the Snailz platform you agree that Snailz may send you up to 10 text messages related to your transaction. You are responsible for any fees or costs incurred when accepting or replying to these text messages.',
]
