export const LANDING_PATH = '/'
export const SEARCH_PATH = '/search'
export const REWARDS_PATH = '/rewards'
export const SALONS_PATH = '/salons'
export const FOR_SALONS_PATH = '/for-salons'
export const FAQ_PATH = '/faq'
export const PRIVACY_PATH = '/privacy'
export const TERMS_PATH = '/terms'
export const ACCESSIBILITY_STATMENT_PATH = '/accessibility-statement'
export const GIFT_CARD_PATH = '/gift-card'
export const HOW_SNAILZ_WORKS_PATH = '/how-snailz-works'

export const PROFILE_PATH = '/account/profile'
export const PAYMENT_METHODS_PATH = '/account/cards'
export const APPOINTMENTS_PATH = '/account/upcoming'
export const PAST_APPOINTMENTS_PATH = '/account/past'
